"""add post.type

Revision ID: f172a2ea80e8
Revises: 
Create Date: 2019-08-02 07:38:25.061842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f172a2ea80e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('type', sa.Enum('post', 'review'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'type')
    # ### end Alembic commands ###
